exports.ERROR_CODES = {
  VALIDATION_ERROR_CODE: 400,
  UNAUTHORIZED_ERROR_CODE: 401,
  FORBIDDEN_ERROR_CODE: 403,
  NOT_FOUND_ERROR_CODE: 404,
  DUPLICATE_ERROR_CODE: 409,
  SERVER_ERROR_CODE: 500,
};
